apiVersion: v1
kind: Pod
metadata:
  name: pod-failed
spec:
  restartPolicy: Never
  containers:
    - name: alpine
      image: alpine:latest
      command:
        - echox
      resources:
        limits:
          cpu: 50m
          memory: 100M
        requests:
          cpu: 50m
          memory: 100M
