apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
  labels:
    app: podinfo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: podinfo
  template:
    metadata:
      labels:
        app: podinfo
    spec:
      containers:
        - name: podinfo
          image: hirokimatsumoto/podinfo:latest
          imagePullPolicy: IfNotPresent
          command:
            - ./podinfo
            - --port=9898
            - --level=debug
          ports:
            - containerPort: 9898
          resources:
            limits:
              cpu: 50m
              memory: 100G
            requests:
              cpu: 50m
              memory: 100G
          readinessProbe:
            httpGet:
              path: /readyz
              port: 9898
            failureThreshold: 1
            periodSeconds: 1
            initialDelaySeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9898
            failureThreshold: 1
            periodSeconds: 5
            initialDelaySeconds: 10
