apiVersion: v1
kind: Pod
metadata:
  name: cluster-pod
  labels:
    app: work
spec:
  containers:
  - name: cluster-pod
    image: byrnedo/alpine-curl:latest
    command: ["/bin/sh"]
    args: ["-c", "trap 'exit 0' 15;while true; do exec sleep 100 & wait $!; done"]
